---
- name: install ntp
  yum:
    name: ntp
    state: installed
  when: ntpd_enabled|bool

- name: ensure ntp is running and enabled
  service:
    name: ntpd
    state: started
    enabled: yes
  when: ntpd_enabled|bool

- name: ensure ntp is not running or enabled
  service:
    name: ntpd
    state: stopped
    enabled: no
  when: not ntpd_enabled|bool
